### ISSUE TITLE
Trouble following README.md instructions

### ISSUE THREAD

**Issue by Alvareto136** [plata/phoenicis-app-flatpak-generator#1]
Hi, continuing this issue and following this comment:

> If you would like to have a separate flatpak for Epic Games Launcher, try 
> https://github.com/plata/phoenicis-app-flatpak-generator.
> 
> _Originally posted by @plata
> https://github.com/flathub/org.phoenicis.playonlinux/issues/12#issuecomment-644150917_

I barely know anything about programming, but I've been trying to install Epic Games Launcher building a flatpak version of it using this **phoenicis-app-flatpak-generator**, because that's what I was suggested. So trying to follow the instructions, line by line, this happened:
![Schermata da 2020-06-16 10-07-52](https://user-images.githubusercontent.com/66923863/84793120-5c90e900-afba-11ea-8fe4-7a44258b3e54.png)

The first message says that the phoenicis clone is already made (because I already ran that command) but that's not the problem though. The problem is that when I run this command `mvn package -DskipTests` it gives out this message `bash: mvn: comando non trovato` which means "command not found" so I don't know if I should run the next command which is `cd ..`

Please take into account that I don't understand many programming concepts so just tell me what I can do, exactly as I should do it.

**Comment by plata** [comment]
*NOTE:* This is assuming that you are on Ubuntu/Mint. Otherwise, you must adapt the `apt` commands.

"command not found": you must install maven (`sudo apt install maven`)

Apart from that, you need flatpak-builder and the flatpak runtime and extensions:
```
sudo add-apt-repository ppa:alexlarsson/flatpak -y
sudo apt update -q
sudo apt install -y flatpak flatpak-builder
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak -y install flathub org.freedesktop.Platform/x86_64/19.08
flatpak -y install flathub org.freedesktop.Sdk/x86_64/19.08
flatpak -y install flathub org.freedesktop.Sdk.Compat.i386/x86_64/19.08
flatpak -y install flathub org.freedesktop.Sdk.Extension.toolchain-i386/x86_64/19.08
flatpak -y install flathub org.freedesktop.Sdk.Extension.openjdk11/x86_64/19.08
flatpak -y install flathub org.freedesktop.Platform.Compat.i386/x86_64/19.08
flatpak -y install flathub org.freedesktop.Platform.GL32.nvidia-410-73/x86_64/1.4
```

After that, run the following commands in an empty directory:
```
git clone https://github.com/PhoenicisOrg/scripts.git
python phoenicis-app-flatpak-generator.py -i scripts/Applications/Games/Epic\ Games\ Launcher/Online/ -o output
cd output
git clone https://github.com/PhoenicisOrg/phoenicis.git
cd phoenicis
mvn package -DskipTests
cd ..
cp phoenicis/phoenicis-dist/target/phoenicis-flatpak.zip .
flatpak-builder build-dir org.phoenicis.epic_games_launcher.yml --force-clean --user --install
```
Now, you should be able to run
```
flatpak run org.phoenicis.epic_games_launcher
```

**EDIT:** Do not use `flatpak-openldap` branch (has been merged to master).

**Comment by Alvareto136** [comment]
Crap, I forgot, sorry, the OS I'm using is **Endeless 3.8.3**, in this OS what would the _apt_ commands be like?

And also, apart form those _apt_ commands the rest is the same, right?

Sorry for the inconvenience, I'm an idiot when it comes to this kind of stuff 😅

**Comment by plata** [comment]
@LeandroStanger I don't know Endless OS. Can you help @Alvareto136?
